version: '3'
services:
  postgres:
    restart: always
    image: postgres:15.5-alpine
    container_name: sponsor_pg
    shm_size: 1gb
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '23532:5432'
    volumes:
      - $POSTGRES_DATA_VOLUME:/var/lib/postgresql/data
  hasura:
    restart: always
    image: hasura/graphql-engine:${HASURA_VERSION}
    container_name: sponsor_hasura
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DATABASE'
      SPONSOR_TRANSACTION_DATABASE_URL: 'postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DATABASE'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: 'info'
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_ADMIN_SECRET
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: 'startup, http-log, webhook-log, websocket-log, query-log'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_SERVER_PORT: 8080
      ACTION_BASE_URL: ${ACTION_BASE_URL:-http://gateway.docker.internal:2980}
    ports:
      - '$HASURA_PORT:8080'
    extra_hosts:
      - 'gateway.docker.internal:host-gateway'
volumes:
  pgdata: {}
